[project]
name = "ollama-to-openai"
version = "0.1.0"
description = "Ollama to OpenAI proxy server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "openai>=1.108.2",
    "pyyaml>=6.0.2",
]
